services:
  metaphactory:
    # metaphactory overwrites here
    ports:
      - "10214:8080"
    #  - "10213:8443"
    #mem_limit: 2g
    #mem_reservation: 2g
    #environment:
    # Uncomment the following line(s) to activate bundled apps
    # - MP_APP_AWS_SERVICES=/bundled/apps/aws-services
    # - MP_APP_EIA=/bundled/apps/enterprise-information-architecture
    #extra_hosts:
    #  - "hostmachine:172.17.0.1"

